openapi: 3.0.1
info:
  description: TiDB Cloud Serverless Database Audit Logging Open API
  title: TiDB Cloud Serverless Database Audit Logging Open API
  version: v1beta1
servers:
- url: https://serverless.tidbapi.com/
tags:
- name: AuditLogService
paths:
  /v1beta1/clusters/{clusterId}/auditlogs:
    get:
      operationId: AuditLogService_ListAuditLogs
      parameters:
      - description: Required. The ID of the cluster.
        in: path
        name: clusterId
        required: true
        schema:
          type: string
      - description: Optional. The UTC date of the audit logs in the format of `YYYY-MM-DD`
          (e.g. 2025-01-01).
        in: query
        name: date
        schema:
          type: string
      - description: "Optional. The maximum number to return, default is 100, and\
          \ the maximum is 1000."
        in: query
        name: pageSize
        schema:
          format: int32
          type: integer
      - description: Optional. The page token from the previous response for pagination.
        in: query
        name: pageToken
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAuditLogsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      summary: List database audit logs.
      tags:
      - AuditLogService
  /v1beta1/clusters/{clusterId}/auditlogs:download:
    post:
      operationId: AuditLogService_DownloadAuditLogs
      parameters:
      - description: Required. The ID of the cluster.
        in: path
        name: clusterId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditLogService.DownloadAuditLogsBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadAuditLogsResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      summary: Generate audit logs download url
      tags:
      - AuditLogService
      x-codegen-request-body-name: body
  /v1beta1/clusters/{clusterId}/auditlogs/filterRules/{name}:
    delete:
      operationId: AuditLogService_DeleteAuditLogFilterRule
      parameters:
      - description: Required.
        in: path
        name: clusterId
        required: true
        schema:
          type: string
      - description: Required. The name of the filter rule.
        in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogFilterRule'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      summary: Delete audit log filter rule.
      tags:
      - AuditLogService
    get:
      operationId: AuditLogService_GetAuditLogFilterRule
      parameters:
      - description: Required.
        in: path
        name: clusterId
        required: true
        schema:
          type: string
      - description: Required. The name of the filter rule.
        in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogFilterRule'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      summary: Get audit log filter rule.
      tags:
      - AuditLogService
    patch:
      operationId: AuditLogService_UpdateAuditLogFilterRule
      parameters:
      - description: Required.
        in: path
        name: clusterId
        required: true
        schema:
          type: string
      - description: Required. The name of the filter rule.
        in: path
        name: name
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditLogService.UpdateAuditLogFilterRuleBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogFilterRule'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      summary: Update audit log filter rule.
      tags:
      - AuditLogService
      x-codegen-request-body-name: body
  /v1beta1/clusters/{clusterId}/auditlogs/filterRules:
    get:
      operationId: AuditLogService_ListAuditLogFilterRules
      parameters:
      - description: Required.
        in: path
        name: clusterId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAuditLogFilterRulesResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      summary: List audit log filter rules.
      tags:
      - AuditLogService
    post:
      operationId: AuditLogService_CreateAuditLogFilterRule
      parameters:
      - description: Required.
        in: path
        name: clusterId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditLogService.CreateAuditLogFilterRuleBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogFilterRule'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: An unexpected error response.
      summary: Create audit log filter rule.
      tags:
      - AuditLogService
      x-codegen-request-body-name: body
components:
  schemas:
    Any:
      additionalProperties:
        type: object
      example:
        '@type': '@type'
      properties:
        '@type':
          type: string
      type: object
    AuditLog:
      example:
        size: 0
        name: name
        url: url
      properties:
        name:
          description: The name of the audit log.
          type: string
        size:
          description: The size in bytes of the audit log.
          format: int64
          type: integer
        url:
          description: download url of the audit log.
          type: string
      type: object
    AuditLogFilter:
      description: "Message for filter, only the entry matching all the conditions\
        \ will be audit logged."
      example:
        statusCodes:
        - 0
        - 0
        tables:
        - tables
        - tables
        classes:
        - classes
        - classes
      properties:
        classes:
          description: OPTIONAL. Classes to include in the filter combined with an
            OR relationship.
          items:
            type: string
          type: array
        tables:
          description: OPTIONAL. Tables to include in the filter combined with an
            OR relationship.
          items:
            type: string
          type: array
        statusCodes:
          description: OPTIONAL. Status codes to include in the filter combined with
            an OR relationship.
          items:
            format: int32
            type: integer
          type: array
      type: object
    AuditLogFilterRule:
      example:
        name: name
        disabled: true
        filters:
        - statusCodes:
          - 0
          - 0
          tables:
          - tables
          - tables
          classes:
          - classes
          - classes
        - statusCodes:
          - 0
          - 0
          tables:
          - tables
          - tables
          classes:
          - classes
          - classes
        users:
        - users
        - users
      properties:
        name:
          description: Required. Unique name of the filter rule within a cluster.
          type: string
        users:
          items:
            type: string
          title: "Required. Database users in the format <user>@<host> or <user> (host\
            \ defaults to %), e.g., %@%, 4C3z3cdMX8iXks5.root"
          type: array
        filters:
          description: "Required. List of filters combined with an OR relationship.\
            \ Set filters to [{}] will filter all logs."
          items:
            $ref: '#/components/schemas/AuditLogFilter'
          type: array
        disabled:
          description: OUTPUT_ONLY. Indicates whether the filter rule is disabled.
          readOnly: true
          type: boolean
      required:
      - filters
      - name
      - users
      type: object
    AuditLogService.CreateAuditLogFilterRuleBody:
      properties:
        filterRule:
          allOf:
          - $ref: '#/components/schemas/AuditLogFilterRule'
          description: Required. The filter rule to create.
          type: object
      required:
      - filterRule
      type: object
    AuditLogService.DownloadAuditLogsBody:
      properties:
        auditLogNames:
          description: Required. The name of the audit logs to download. Up to 100
            audit logs can be downloaded at the same time.
          items:
            type: string
          type: array
      required:
      - auditLogNames
      type: object
    AuditLogService.UpdateAuditLogFilterRuleBody:
      properties:
        filters:
          description: "OPTIONAL. List of filters combined with an OR relationship.\
            \ Set filters to [{}] will filter all logs."
          items:
            $ref: '#/components/schemas/AuditLogFilter'
          type: array
        users:
          items:
            type: string
          title: "Required. Database users in the format <user>@<host> or <user> (host\
            \ defaults to %), e.g., %@%, 4C3z3cdMX8iXks5.root"
          type: array
        disabled:
          description: OPTIONAL. Indicates whether the filter rule is disabled.
          nullable: true
          type: boolean
      type: object
    DownloadAuditLogsResponse:
      example:
        auditLogs:
        - size: 0
          name: name
          url: url
        - size: 0
          name: name
          url: url
      properties:
        auditLogs:
          description: The audit logs with the download url.
          items:
            $ref: '#/components/schemas/AuditLog'
          type: array
      type: object
    ListAuditLogFilterRulesResponse:
      example:
        filterRules:
        - name: name
          disabled: true
          filters:
          - statusCodes:
            - 0
            - 0
            tables:
            - tables
            - tables
            classes:
            - classes
            - classes
          - statusCodes:
            - 0
            - 0
            tables:
            - tables
            - tables
            classes:
            - classes
            - classes
          users:
          - users
          - users
        - name: name
          disabled: true
          filters:
          - statusCodes:
            - 0
            - 0
            tables:
            - tables
            - tables
            classes:
            - classes
            - classes
          - statusCodes:
            - 0
            - 0
            tables:
            - tables
            - tables
            classes:
            - classes
            - classes
          users:
          - users
          - users
      properties:
        filterRules:
          items:
            $ref: '#/components/schemas/AuditLogFilterRule'
          type: array
      type: object
    ListAuditLogsResponse:
      example:
        auditLogs:
        - size: 0
          name: name
          url: url
        - size: 0
          name: name
          url: url
        nextPageToken: nextPageToken
      properties:
        auditLogs:
          description: The audit logs without the download url.
          items:
            $ref: '#/components/schemas/AuditLog'
          type: array
        nextPageToken:
          description: Token provided to retrieve the next page of results.
          type: string
      type: object
    Status:
      example:
        code: 6
        details:
        - '@type': '@type'
        - '@type': '@type'
        message: message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        details:
          items:
            $ref: '#/components/schemas/Any'
          type: array
      type: object
x-original-swagger-version: "2.0"
